version: '3.8'

services:
  fasttrack-app:
    # Production overrides
    environment:
      - LOG_LEVEL=INFO
      - FASTAPI_RELOAD=false
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
    labels:
      - "com.docker.compose.service=production"
